CREATE TABLE BOARD.MEMBER (
	MEMBERID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL,
    REGDATE DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT character set = utf8;